// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Download struct {
	Name string `json:"name"`
	Data string `json:"data"`
}

type File struct {
	Name      string     `json:"name"`
	Key       string     `json:"key"`
	Type      string     `json:"type"`
	IsDir     bool       `json:"isDir"`
	Size      *int       `json:"size,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

type UpdateFileInput struct {
	Key         string `json:"key"`
	Destination string `json:"destination"`
}
