name: Deploy web to ghcr.io

on:
  push:
    branches:
      - master
    paths:
      - web/**
      - .github/workflows/deploy_web.yml

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: generate .env
        run: |
          touch .env
          echo "NEXT_PUBLIC_GRAPHQL_URL=${{ secrets.NEXT_PUBLIC_GRAPHQL_URL }}" >> .env
          echo "NEXT_PUBLIC_STORAGE_URL=${{ secrets.NEXT_PUBLIC_STORAGE_URL }}" >> .env
          echo "NEXT_PUBLIC_UPLOAD_URL=${{ secrets.NEXT_PUBLIC_UPLOAD_URL }}" >> .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/minecore-web:latest
            ghcr.io/${{ github.repository_owner }}/minecore-web:1.1.1
